name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:${{ github.sha }}

      # 若需要多架构，确认单平台通过后取消以下注释：
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Build and Push (multi-arch)
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
      #     tags: |
      #       docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:latest
      #       docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:${{ github.sha }}