name: dev Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Github Code
        uses: actions/checkout@v3

      - name: Set Up Golang Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.7

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/parse-video:${{ github.sha }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8